                                                                                                                                                                                                                                                                                        #include <stdio.h>
                                                                                                                                                                                                                                                                                        #include <ctype.h>
                                                                                                                                                                                                                                                                                        int main(){
                                                                                                                                                                                                                                                                                            char c;
                                                                                                                                                                                                                                                                                            int a=0;
                                                                                                                                                                                                                                                                                            while(isdigit(c=getchar())) 
                                                                                                                                                                                                                                                                                                a++;
                                                                                                                                                                                                                                                                                            printf("a=%i\n",a);
                                                                                                                                                                                                                                                                                            ungetc(c,stdin);
                                                                                                                                                                                                                                                                                            putchar(getchar());

                                                                                                                                                                                                                                                                                        }